import {
  Music,
  Cpu,
  Utensils,
  Trophy,
  Flame,
  Landmark,
} from "lucide-react";

export const INDIAN_EVENTS = [
  {
    id: "1",
    title: "Sunburn Festival 2026",
    category: "Music",
    icon: Music,
    location: "Vagator Beach, Goa",
    date: "2026-12-27",
    price: 4999,
    color: "#e040fb",
    accent: "#ff6090",
    poster: "/events/sunburn.png",
    description: "Asia's premier electronic dance music festival returns to Goa with world-class DJs, stunning beachside stages, and an unforgettable vibe.",
    badge: "🔥 Trending",
    longDescription: "Get ready for the ultimate musical experience at Sunburn Festival 2026! Spread across 4 days at the beautiful Vagator Beach in Goa, this year's festival brings together the top global artists in electronic dance music. Expect massive stages, mesmerizing visual effects, breathtaking pyrotechnics, and an electrifying crowd from all over the world.",
  },
  {
    id: "2",
    title: "Diwali Night Gala",
    category: "Cultural",
    icon: Landmark,
    location: "Jawaharlal Nehru Stadium, Mumbai",
    date: "2026-10-20",
    price: 2499,
    color: "#ffd740",
    accent: "#ff6d00",
    poster: "/events/diwali.png",
    description: "An extravagant Diwali celebration featuring live performances, fireworks, traditional dance, and a grand mela.",
    badge: "✨ Cultural",
    longDescription: "Join us for the most spectacular Diwali Night Gala in Mumbai! Witness the sky illuminate with grand fireworks displays, enjoy mesmerizing live musical and traditional dance performances, and immerse yourself in the festive spirit. Enjoy extravagant feasts, shop at our grand mela for unique handicrafts, and celebrate the festival of lights with thousands of fellow revellers.",
  },
  {
    id: "3",
    title: "India Tech Summit 2026",
    category: "Technology",
    icon: Cpu,
    location: "KTPO Convention Centre, Bangalore",
    date: "2026-09-15",
    price: 7999,
    color: "#40c4ff",
    accent: "#00b0ff",
    poster: "/events/tech-summit.png",
    description: "India's largest technology conference bringing together visionaries, innovators and entrepreneurs from across the globe.",
    badge: "🚀 Featured",
    longDescription: "The India Tech Summit 2026 is the premier gathering for technology enthusiasts, startup founders, and global tech leaders. Dive into deep-dive workshops on AI, Machine Learning, Web3, and cutting-edge software development. Network with industry titans, discover the latest innovations at the startup expo, and gain insights from high-impact keynote sessions.",
  },
  {
    id: "4",
    title: "Kathak Mahotsav",
    category: "Classical Dance",
    icon: Flame,
    location: "Kamani Auditorium, New Delhi",
    date: "2026-11-05",
    price: 1499,
    color: "#ff6e40",
    accent: "#ff3d00",
    poster: "/events/kathak.png",
    description: "A grand celebration of classical Kathak dance featuring legendary maestros and the finest young performers.",
    badge: "🎭 Classical",
    longDescription: "Experience the grace, rhythm, and storytelling of India's classical heritage at Kathak Mahotsav. Hosted at the prestigious Kamani Auditorium, this multi-day festival features awe-inspiring performances by legendary Kathak maestros alongside rising stars. The event highlights intricate footwork, expressive abhinaya, and soul-stirring live classical music accompaniment.",
  },
  {
    id: "5",
    title: "IPL Season Opener 2026",
    category: "Sports",
    icon: Trophy,
    location: "Wankhede Stadium, Mumbai",
    date: "2026-03-28",
    price: 3499,
    color: "#69f0ae",
    accent: "#00e676",
    poster: "/events/ipl.png",
    description: "Witness the electrifying opening night of IPL 2026 with fireworks, celebrity appearances, and edge-of-your-seat cricket.",
    badge: "🏏 Sports",
    longDescription: "The wait is over! Experience the thrill of the Indian Premier League right at the stadium. The IPL Season Opener 2026 promises a breathtaking inauguration ceremony with Bollywood celebrities, a mesmerizing laser show, and the highly anticipated opening match. Feel the unmatched stadium energy, chant for your favorite teams, and witness cricketing history live in action.",
  },
  {
    id: "6",
    title: "India Food Mela 2026",
    category: "Food & Cuisine",
    icon: Utensils,
    location: "Island Grounds, Chennai",
    date: "2026-08-10",
    price: 799,
    color: "#ff8f00",
    accent: "#ff6f00",
    poster: "/events/food-mela.png",
    description: "Savour the rich tapestry of Indian culinary tradition — 500+ stalls, live cooking demos, and top chefs from 28 states.",
    badge: "🍛 Popular",
    longDescription: "Embark on a culinary journey across India without leaving Chennai! The India Food Mela 2026 brings together authentic cuisines, street food gems, and royal delicacies from all 28 states. From fiery Chettinad dishes to rich Awadhi kebabs, experience diverse flavors through 500+ food stalls. Attend masterclasses by Michelin-starred chefs, enjoy cultural performances, and indulge in a gastronomic paradise.",
  },
];
